### ISSUE TITLE
[Bug?]: @yarnpkg/core: Property 'env' is missing in type 'CommandContext' but required in type 'BaseContext'

### ISSUE THREAD

**Issue by milahu** [yarnpkg/berry#4298]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

works with `@yarnpkg/core@3.1.x`

with `@yarnpkg/core@3.2.0` ...

```
$ npm run build 

> repro-yarnpkg-core-property-env-is-missing-in-type-commandcontext@1.0.0 build
> tsc --build

node_modules/@yarnpkg/core/lib/Plugin.d.ts:135:35 - error TS2344: Type 'CommandContext' does not satisfy the constraint 'BaseContext'.
  Property 'env' is missing in type 'CommandContext' but required in type 'BaseContext'.

135     commands?: Array<CommandClass<CommandContext>>;
                                      ~~~~~~~~~~~~~~

  node_modules/clipanion/lib/advanced/Cli.d.ts:21:5
    21     env: Record<string, string | undefined>;
           ~~~
    'env' is declared here.


Found 1 error.
```

### To reproduce

```sh
#! /bin/sh

cd $(mktemp -d)

cat >package.json <<"EOF"
{
  "name": "repro-yarnpkg-core-property-env-is-missing-in-type-commandcontext",
  "version": "1.0.0",
  "scripts": {
    "build": "tsc --build"
  },
  "devDependencies": {
    "typescript": "^4.6.3"
  },
  "dependencies": {
    "@yarnpkg/core": "3.2.0"
  }
}
EOF

cat >tsconfig.json <<"EOF"
{
    "compilerOptions": {
        "outDir": "./dist",
        "pretty": true,
        "target": "es2017",
        "lib": [
            "es2017",
            "dom"
        ],
        "allowSyntheticDefaultImports": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "importHelpers": true,
        "strict": true,
        "noImplicitAny": false,
    },
    "include": [
        "./index.ts",
    ]
}
EOF

cat >index.ts <<"EOF"
import * as yarnCore from '@yarnpkg/core';

const structUtils = yarnCore.structUtils;
const parseDescriptor = structUtils.parseDescriptor;

parseDescriptor("cowsay@^1.5.0, cowsay@1.5.0");
EOF

npm install

npm run build
```

<details>
<summary>sherlock is not working: internal error</summary>

what did i try?

```js
await packageJsonAndInstall({
  "devDependencies": {
    "typescript": "^4.6.3"
  },
  "dependencies": {
    "@yarnpkg/core": "3.2.0"
  },
  "scripts": {
    "build": "tsc --build"
  },
});

// based on tsconfig.json from
// https://github.com/snyk/nodejs-lockfile-parser
await fs.writeFile(`tsconfig.json`, `
{
    "compilerOptions": {
        "outDir": "./dist",
        "pretty": true,
        "target": "es2017",
        "lib": [
            "es2017",
            "dom"
        ],
        "allowSyntheticDefaultImports": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "importHelpers": true,
        "strict": true,
        "noImplicitAny": false, // Needed to compile tap
    },
    "include": [
        "./index.ts",
    ]
}
`);

await fs.writeFile(`index.ts`, `
import * as yarnCore from '@yarnpkg/core';

const structUtils = yarnCore.structUtils;
const parseDescriptor = structUtils.parseDescriptor;

parseDescriptor("cowsay@^1.5.0, cowsay@1.5.0");
`);

await yarn(`build`)
```

</details>

### Environment

```shell
System:
    OS: Linux 5.15 NixOS 22.05 (Quokka)
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  Binaries:
    Node: 16.14.0 - /tmp/xfs-14b4b910/node
    Yarn: 2.4.3 - /tmp/xfs-14b4b910/yarn
    npm: 8.3.1 - /run/current-system/sw/bin/npm
```

**Comment by viceice** [comment]
Seeing the same issue (caused by typescript strict null checks)

- https://github.com/renovatebot/renovate/runs/6151777355?check_suite_focus=true
- https://github.com/renovatebot/renovate/pull/15284

**Comment by rarkins** [comment]
Problem still present in 3.2.2:

```
$ tsc --noEmit
node_modules/@yarnpkg/core/lib/Plugin.d.ts:138:35 - error TS2344: Type 'CommandContext' does not satisfy the constraint 'BaseContext'.
  Property 'env' is missing in type 'CommandContext' but required in type 'BaseContext'.

138     commands?: Array<CommandClass<CommandContext>>;
                                      ~~~~~~~~~~~~~~

  node_modules/clipanion/lib/advanced/Cli.d.ts:21:5
    21     env: Record<string, string | undefined>;
           ~~~
    'env' is declared here.


Found 1 error in node_modules/@yarnpkg/core/lib/Plugin.d.ts:138
```

**Comment by yarnbot** [comment]
Hi! 👋

This issue looks stale, and doesn't feature the `reproducible` label - which implies that you didn't provide a working reproduction using [Sherlock](https://yarnpkg.com/advanced/sherlock). As a result, it'll be closed in a few days unless a maintainer explicitly vouches for it or you edit your first post to include a formal reproduction (you can use the [playground](http://yarnpkg.com/playground) for that).

Note that we require Sherlock reproductions for long-lived issues (rather than standalone git repositories or similar) because we're a small team. Sherlock gives us the ability to check which bugs are still affecting the master branch at any given point, and decreases the amount of code we need to run on our own machines (thus leading to faster bug resolutions). It helps us help you! 😃

If you absolutely *cannot* reproduce a bug on Sherlock (for example because it's a Windows-only issue), a maintainer will have to manually add the `upholded` label. Thanks for helping us triaging our repository! 🌟

**Comment by merceyz** [comment]
This was fixed in https://github.com/yarnpkg/berry/pull/4331

**Comment by viceice** [comment]
I still see this issue when using `@yarnpkg/core@3.2.2` 

- https://github.com/renovatebot/renovate/pull/16459

**Comment by merceyz** [comment]
I [pushed a commit](https://github.com/yarnpkg/berry/commit/4dd358365c9223685892a761198a08686e1d528e) to lock the `clipanion` version which should solve the issue, it will be released as v3.2.3 in a few days.

**Comment by alamothe** [comment]
I don't think it solves it, I am simply getting a different compile error now:
```
src/index.ts:5:13 - error TS2322: Type 'typeof ConfigureRegistryCommand' is not assignable to type 'CommandClass<CommandContext>'.
  Construct signature return types 'ConfigureRegistryCommand' and 'Command<CommandContext>' are incompatible.
    The types of 'cli' are incompatible between these types.
      Type 'MiniCli<BaseContext>' is not assignable to type 'MiniCli<CommandContext>'.
        Type 'MiniCli<BaseContext>' is not assignable to type '{ definitions(): Definition[]; error(error: Error, opts?: { command?: Command<CommandContext> | null | undefined; } | undefined): string; format(colored?: boolean | undefined): ColorFormat; process(input: string[]): Command<...>; run(input: string[], context?: Partial<...> | undefined): Promise<...>; usage(command?:...'.
          The types of 'process(...).context' are incompatible between these types.
            Type 'BaseContext' is not assignable to type 'CommandContext'.
```
