### ISSUE TITLE
[Bug] webpack@4.44.1 does not work with `node-modules` linker in a monorepo

### ISSUE THREAD

**Issue by ikatyang** [yarnpkg/berry#1706]
**Describe the bug**

webpack@4.44.1 does not work with `node-modules` linker in a monorepo, the `webpack` is somehow NOT hoisted while its dependency `terser-webpack-plugin` with `webpack` as a `peerDependencies` is still hoisted.

**To Reproduce**

<details>
  <summary>Reproduction</summary>

  ```js repro
  require('fs').writeFileSync('.yarnrc.yml', 'nodeLinker: node-modules')

  await packageJson({ name: 'root', workspaces: ['packages/*'] })
  await packageJson(
    {
      name: 'package-a',
      devDependencies: {
        "webpack": "4.44.1",
        "webpack-cli": "3.3.12",
      },
    },
    { cwd: 'packages/package-a' },
  )
  await yarn('install', { maxBuffer: 64 * 1024 * 1024 })

  await expect(yarn(`node`, `packages/package-a/node_modules/.bin/webpack-cli`))
    .rejects.not.toThrow(`Cannot find module 'webpack/lib/RequestShortener'`)
  ```
</details>

**Screenshots**

```
Error: Cannot find module 'webpack/lib/RequestShortener'
Require stack:
- ~/node_modules/terser-webpack-plugin/dist/index.js
- ~/node_modules/terser-webpack-plugin/dist/cjs.js
- ~/packages/workspace-a/node_modules/webpack/lib/WebpackOptionsDefaulter.js
- ~/packages/workspace-a/node_modules/webpack/lib/webpack.js
- ~/packages/workspace-a/node_modules/webpack-cli/bin/utils/validate-options.js
- ~/packages/workspace-a/node_modules/webpack-cli/bin/utils/convert-argv.js
- ~/packages/workspace-a/node_modules/webpack-cli/bin/cli.js
```

**Environment**

 - Yarn version 2.1.1

**Additional context**

- `webpack@4.44.0` works fine.
- the issue is probably introduced by https://github.com/webpack/webpack/pull/11190, which adds peerDep `webpack-cli` to `webpack`
- there is a peerDep `webpack` in `webpack-cli`

**Comment by yarnbot** [comment]
This issue reproduces on master:
```
Error: expect(received).rejects.not.toThrow(expected)

Expected substring: not "Cannot find module 'webpack/lib/RequestShortener'"
Received message:       "Command failed: /usr/bin/node /github/workspace/scripts/actions/../run-yarn.js node packages/package-a/node_modules/.bin/webpack-cli
/tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

Error: Cannot find module 'webpack/lib/RequestShortener'
Require stack:
- /tmp/tmp-27V3gtSywBTOMZ/node_modules/terser-webpack-plugin/dist/index.js
- /tmp/tmp-27V3gtSywBTOMZ/node_modules/terser-webpack-plugin/dist/cjs.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/WebpackOptionsDefaulter.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/webpack.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/utils/validate-options.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/utils/convert-argv.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js
Require stack:
- /tmp/tmp-27V3gtSywBTOMZ/node_modules/terser-webpack-plugin/dist/index.js
- /tmp/tmp-27V3gtSywBTOMZ/node_modules/terser-webpack-plugin/dist/cjs.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/WebpackOptionsDefaulter.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/webpack.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/utils/validate-options.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/utils/convert-argv.js
- /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.external_module_.Module._resolveFilename (/github/workspace/.pnp.js:40213:54)
    at Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.external_module_.Module._load (/github/workspace/.pnp.js:40068:36)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/tmp/tmp-27V3gtSywBTOMZ/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/tmp/tmp-27V3gtSywBTOMZ/node_modules/terser-webpack-plugin/dist/index.js:16:48)
    at Module._compile (/tmp/tmp-27V3gtSywBTOMZ/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.external_module_.Module._load (/github/workspace/.pnp.js:40068:36)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/tmp/tmp-27V3gtSywBTOMZ/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/tmp/tmp-27V3gtSywBTOMZ/node_modules/terser-webpack-plugin/dist/cjs.js:3:16)
    at Module._compile (/tmp/tmp-27V3gtSywBTOMZ/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.external_module_.Module._load (/github/workspace/.pnp.js:40068:36)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (/tmp/tmp-27V3gtSywBTOMZ/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.apply (/tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/WebpackOptionsDefaulter.js:308:27)
    at WebpackOptionsApply.process (/tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/WebpackOptionsApply.js:481:16)
    at webpack (/tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack/lib/webpack.js:57:48)
    at processOptions (/tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js:272:16)
    at /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/tmp/tmp-27V3gtSywBTOMZ/node_modules/yargs/yargs.js:576:18)
    at /tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/tmp/tmp-27V3gtSywBTOMZ/packages/package-a/node_modules/webpack-cli/bin/cli.js:366:3) {
  code: 'MODULE_NOT_FOUND'
}

"

      40211 |         } else {
      40212 |           if (path === null) throw new Error(`Assertion failed: Expected the path to be set`);
    > 40213 |           resolution = originalModuleResolveFilename.call(external_module_.Module, request, module || makeFakeParent(path), isMain);
            |                                                      ^
      40214 |         }
      40215 |       } catch (error) {
      40216 |         firstError = firstError || error;

      at Function.external_module_.Module._resolveFilename (../../github/workspace/.pnp.js:40213:54)
      at Function.external_module_.Module._load (../../github/workspace/.pnp.js:40068:36)
      at require (node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
      at Object.<anonymous> (node_modules/terser-webpack-plugin/dist/index.js:16:48)
      at Module._compile (node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
      at Function.external_module_.Module._load (../../github/workspace/.pnp.js:40068:36)
      at require (node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
      at Object.<anonymous> (node_modules/terser-webpack-plugin/dist/cjs.js:3:16)
      at Module._compile (node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
      at Function.external_module_.Module._load (../../github/workspace/.pnp.js:40068:36)
      at require (node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
      at Object.apply (packages/package-a/node_modules/webpack/lib/WebpackOptionsDefaulter.js:308:27)
      at WebpackOptionsApply.process (packages/package-a/node_modules/webpack/lib/WebpackOptionsApply.js:481:16)
      at webpack (packages/package-a/node_modules/webpack/lib/webpack.js:57:48)
      at processOptions (packages/package-a/node_modules/webpack-cli/bin/cli.js:272:16)
      at packages/package-a/node_modules/webpack-cli/bin/cli.js:364:3
      at Object.parse (node_modules/yargs/yargs.js:576:18)
      at packages/package-a/node_modules/webpack-cli/bin/cli.js:49:8
      at Object.<anonymous> (packages/package-a/node_modules/webpack-cli/bin/cli.js:366:3) {
        code: 'MODULE_NOT_FOUND'
      }
    at Object.toThrow (/github/workspace/.yarn/cache/expect-npm-24.8.0-8c7640c562-0ac41999f0.zip/node_modules/expect/build/index.js:242:20)
    at module.exports (evalmachine.<anonymous>:18:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-63f998598d.zip/node_modules/@arcanis/sherlock/lib/executeRepro.js:56:13
    at async executeInTempDirectory (/github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-63f998598d.zip/node_modules/@arcanis/sherlock/lib/executeRepro.js:17:16)
    at async Object.executeRepro (/github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-63f998598d.zip/node_modules/@arcanis/sherlock/lib/executeRepro.js:24:12)
    at async ExecCommand.execute (/github/workspace/.yarn/cache/@arcanis-sherlock-npm-1.0.38-d4f5e2dbf3-63f998598d.zip/node_modules/@arcanis/sherlock/lib/commands/exec.js:25:38)
    at async ExecCommand.validateAndExecute (/github/workspace/.yarn/cache/clipanion-npm-2.0.0-rc.16-b9444aaf89-a57989414f.zip/node_modules/clipanion/lib/advanced/Command.js:161:26)
    at async Cli.run (/github/workspace/.yarn/cache/clipanion-npm-2.0.0-rc.16-b9444aaf89-a57989414f.zip/node_modules/clipanion/lib/advanced/Cli.js:74:24)
    at async Cli.runExit (/github/workspace/.yarn/cache/clipanion-npm-2.0.0-rc.16-b9444aaf89-a57989414f.zip/node_modules/clipanion/lib/advanced/Cli.js:83:28)
```

**Comment by larixer** [comment]
@ikatyang The hoister in V2 does not hoist `webpack` and `webpack-cli`, because they peer depend now on each another and thus form a loop. This is not a bug however, all the dependency constraints are met by the hoister. The bug is somewhere in webpack dependencies, probably inside terser plugin.

**Comment by larixer** [comment]
CC @merceyz

**Comment by larixer** [comment]
Its seems not right that `terser-webpack-plugin` was hoisted to the top though. It might indicate bug in the hoister, I'm checking...
