### ISSUE TITLE
[Feature] yarn plugin remove / friendlier error message for missing plugins

### ISSUE THREAD

**Issue by andreialecu** [yarnpkg/berry#735]
- [ ] I'd be willing to implement this feature
- [ ] This feature can already be implemented through a plugin

**Describe the user story**

Looks like the latest berry now ships with the `workspace-tools` plugin already bundled. 

After updating, I started running into errors such as:

```
yarn workspace workspace1 build-release
Ambiguous Syntax Error: Cannot find who to pick amongst the following alternatives:

  0. yarn workspace <workspaceName> <commandName> ...
  1. yarn workspace <workspaceName> <commandName> ...

While running workspace workspace1 build-release
```

With some help on discord, I found out about that this could happen because the plugin is duplicated between core and the separately installed one.

I looked for a way to remove the plugin, but the documentation doesn't mention what to do, so I attempted to delete the file from `.yarn/plugins`, which led to the following error afterwards when running any `yarn` command:

```bash
$ yarn
Internal Error: Cannot find module '/home/.../.yarn/plugins/@yarnpkg/plugin-workspace-tools.js'
Require stack:
- /home/.../.yarn/releases/yarn-sources.js
Require stack:
- /home/.../.yarn/releases/yarn-sources.js
```

I found the plugin referenced in `.yarnrc.yml` and also removed it from there, which got `yarn` working again.

**Describe the solution you'd like**

It would be nice if a command to remove a plugin was available, perhaps `yarn plugin remove workspace-tools`. With yarn installed globally it may be even harder to figure out how to remove plugins.

Additionally, a friendlier error message than the `cannot find module` would be nice. Perhaps one that would point to `.yarnrc.yml` so users know how to resolve it.

**Describe the drawbacks of your solution**

Can't think of any.

**Describe alternatives you've considered**

Can be solved manually, but the experience is confusing.

**Comment by aaronadamsCA** [comment]
```sh
yarn plugin remove @yarnpkg/plugin-workspace-tools
```

But yes, the error message/scenario is confusing. I upgraded two repositories to Yarn v2.4.2, both had `@yarnpkg/plugin-workspace-tools` installed, one broke and the other continued to work. 🤷‍♂️

**Comment by aaronadamsCA** [comment]
I found that the actual solution was to re-install the plugins after upgrading to v2.4.2.

```sh
yarn plugin import interactive-tools
yarn plugin import workspace-tools
```

It seems plugins are silently versioned. Plugins installed under v2.4.1 broke after `yarn set version latest` upgraded to v2.4.2.
