### PR TITLE
[node-modules] Fixes hoisting when package peer depends on parent itself

### LINKED ISSUE #1706: [Bug] webpack@4.44.1 does not work with `node-modules` linker in a monorepo
**Describe the bug**

webpack@4.44.1 does not work with `node-modules` linker in a monorepo, the `webpack` is somehow NOT hoisted while its dependency `terser-webpack-plugin` with `webpack` as a `peerDependencies` is still hoisted.

**To Reproduce**

<details>
  <summary>Reproduction</summary>

  ```js repro
  require('fs').writeFileSync('.yarnrc.yml', 'nodeLinker: node-modules')

  await packageJson({ name: 'root', workspaces: ['packages/*'] })
  await packageJson(
    {
      name: 'package-a',
      devDependencies: {
        "webpack": "4.44.1",
        "webpack-cli": "3.3.12",
      },
    },
    { cwd: 'packages/package-a' },
  )
  await yarn('install', { maxBuffer: 64 * 1024 * 1024 })

  await expect(yarn(`node`, `packages/package-a/node_modules/.bin/webpack-cli`))
    .rejects.not.toThrow(`Cannot find module 'webpack/lib/RequestShortener'`)
  ```
</details>

**Screenshots**

```
Error: Cannot find module 'webpack/lib/RequestShortener'
Require stack:
- ~/node_modules/terser-webpack-plugin/dist/index.js
- ~/node_modules/terser-webpack-plugin/dist/cjs.js
- ~/packages/workspace-a/node_modules/webpack/lib/WebpackOptionsDefaulter.js
- ~/packages/workspace-a/node_modules/webpack/lib/webpack.js
- ~/packages/workspace-a/node_modules/webpack-cli/bin/utils/validate-options.js
- ~/packages/workspace-a/node_modules/webpack-cli/bin/utils/convert-argv.js
- ~/packages/workspace-a/node_modules/webpack-cli/bin/cli.js
```

**Environment**

 - Yarn version 2.1.1

**Additional context**

- `webpack@4.44.0` works fine.
- the issue is probably introduced by https://github.com/webpack/webpack/pull/11190, which adds peerDep `webpack-cli` to `webpack`
- there is a peerDep `webpack` in `webpack-cli`

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

This PR fixes #1706. The nm hoister currently looses information when package peer depends on the parent package.

**How did you fix it?**

The hoister code was prematurely removing self-references from the tree. Now we keep self-references throughout hoisting process and remove them only when we build node_modules tree.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

**Comment by arcanis** [comment]
Seems like there's an edge case with dependency aliases

**Comment by merceyz** [comment]
> Seems like there's an edge case with dependency aliases

Potentially related https://github.com/yarnpkg/berry/issues/1352

**Comment by larixer** [comment]
> Seems like there's an edge case with dependency aliases
Yes, I have noticed, figuring out where did I break it in a new code...
