### ISSUE TITLE
[Bug?]: When using Yarn 2 with electron, can't import dependencies in main thread

### ISSUE THREAD

**Issue by djsavvy** [yarnpkg/berry#3110]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Imports from the main thread of an electron app cannot be found when using Yarn 2 (though the exact same code work with yarn 1.22). 

### To reproduce

Start with [this commit](https://github.com/djsavvy/yarn-2-electron-main-thread-import-bug-repro/commit/71c8b8534a88f47197faa17b214f7268bd5e76c9) in [this reproduction repo](https://github.com/djsavvy/yarn-2-electron-main-thread-import-bug-repro/). 

The above linked commit is just the final code of the [electron quickstart tutorial](https://www.electronjs.org/docs/tutorial/quick-start), with an extra package imported (`async`). This was created using Yarn 1.22. 

The [next commit](https://github.com/djsavvy/electron-vite-tailwind-starter/commit/08b1c900cac6c82b710c39604ab59f8060c8885c) was created by starting with the previous one, running `yarn set version berry`, then running `yarn` and committing the result. No other changes were made to the code. 

If you try running `yarn start` in the first commit (Yarn 1.22), it works. If you try running in the second commit (Yarn 2.4.2) it instead errors with: 

```
App threw an error during load
Error: Cannot find module 'async'
```

The only difference is switching to Yarn Berry. 

### Environment

```

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 15.14.0 - ~\AppData\Local\Temp\xfs-75eb3334\node.EXE
    Yarn: 2.4.2 - ~\AppData\Local\Temp\xfs-75eb3334\yarn.EXE
    npm: 7.10.0 - ~\AppData\Roaming\npm\npm.CMD

```

### Additional context

Thanks so much for making Yarn Berry. I was successfully able to use it with another project, and the experience is _sooo_ much better than the old installation, especially on Windows. It's an awesome project, and I hope to see its paradigms adopted more in the ecosystem.

**Comment by yarnbot** [comment]
Hi! 👋

This issue looks stale, and doesn't feature the `reproducible` label - which implies that you didn't provide a working reproduction using [Sherlock](https://yarnpkg.com/advanced/sherlock). As a result, it'll be closed in a few days unless a maintainer explicitly vouches for it or you edit your first post to include a formal reproduction (you can use the [playground](http://yarnpkg.com/playground) for that).

Note that we require Sherlock reproductions for long-lived issues (rather than standalone git repositories or similar) because we're a small team. Sherlock gives us the ability to check which bugs are still affecting the master branch at any given point, and decreases the amount of code we need to run on our own machines (thus leading to faster bug resolutions). It helps us help you! 😃

If you absolutely *cannot* reproduce a bug on Sherlock (for example because it's a Windows-only issue), a maintainer will have to manually add the `upholded` label. Thanks for helping us triaging our repository! 🌟
