### ISSUE TITLE
[Bug?]: yarn vscode sdk not working with ts 4.5.2

### ISSUE THREAD

**Issue by ZetraDev** [yarnpkg/berry#3767]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I upgraded the version of ts to 4.5.2, the sdk doesn't work (It will show something like `Cannot find module 'xxx' or its corresponding type declarations.` when I try to import a dependency)

### To reproduce

1. upgrade ts to 4.5.2
2. reload vscode
3. vscode will show the error provided in `Describe the bug`

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 17.1.0 - C:\Users\ADMINI~1\AppData\Local\Temp\xfs-017b96d9\node.CMD
    Yarn: 3.1.0 - C:\Users\ADMINI~1\AppData\Local\Temp\xfs-017b96d9\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Comment by rinsuki** [comment]
It seems duplicate of #3722

**Comment by ZetraDev** [comment]
Is there anyway to fix it?

**Comment by rinsuki** [comment]
currently it was released as RC version, so you can try RC version with `yarn set version 3.2.0-rc.5`, or wait 3.2.0 stable release.

**Comment by merceyz** [comment]
Duplicate of https://github.com/yarnpkg/berry/issues/3722
